### ISSUE TITLE
No, "I'm Done" button at the end of page

### ISSUE THREAD

**Issue by maxgrok** [learn-co-curriculum/the-learn-philosophy#3]
I tried refreshing the page, but could not find an "I'm Done" button.

**Comment by AnnJohn** [comment]
Hi @maxgrok sorry about this issue. Please use the Ask a Question tool in Learn and someone from our support team will get back to you right away. Thanks!

**Comment by maxgrok** [comment]
I already used that. They said to refresh the page, and if that didn't work then to post an issue.

**Comment by maxgrok** [comment]
Just checked and it's been resolved.
